musictable/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views import generic

from . import views
from .models import Song

app_name = 'musictable'
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^song/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail')
]

musictable/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models import Q

#Managers (table level classes)
class SongManager(models.Manager):
	def search(self, q):
		return self.get_queryset().filter((
						Q(title__icontains=q) |
						Q(author__icontains=q) |
						Q(first_line__icontains=q) |
						Q(key_lyric__icontains=q)
					))


# Create your models here.
class Song(models.Model):
	title = models.CharField(db_index=True, max_length=300)
	author = models.CharField(db_index=True, max_length=200, blank=True)
	scripture = models.CharField(db_index=True, max_length=100, blank=True)
	first_line = models.CharField(db_index=True, max_length=300, blank=True)
	key_lyric = models.CharField(db_index=True, max_length=300, blank=True)
	notes = models.CharField(db_index=True, max_length=300, blank=True)
	tags = models.ManyToManyField('Tag', blank=True)
	quarantined = models.BooleanField(default=False)
	objects = SongManager()
	def __str__(self):
		return self.title

class Tag(models.Model):
	name = models.CharField(max_length=50)
	type = models.ForeignKey('TagType')
	def __str__(self):
		return self.name

class TagType(models.Model):
	name = models.CharField(max_length=50)
	def __str__(self):
		return self.name

class Attachment(models.Model):
	name = models.CharField(max_length=50)
	location = models.URLField()
	song = models.ForeignKey('Song',on_delete=models.CASCADE)
	def __str__(self):
			return self.name

musictable/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.views import generic

from .models import Song

# Create your views here.

class IndexView(generic.ListView):
	model = Song
	template_name = 'songs/index.html'
	paginate_by = 50

	def get_queryset(self):
		if self.request.method == "POST":
			q = Song.objects.search(self.request.POST['search'])
		else:
			q = Song.objects.all()
		return q

	def get_context_data(self, **kwargs):
		context = super(IndexView, self).get_context_data(**kwargs)
		# get subset of page range for paginator
		if context['page_obj'] is not None:
			range_max = min(context['paginator'].num_pages-1, context['page_obj'].number+9)
			range_min = max(1, range_max-10);
			context['page_range'] = list(context['paginator'].page_range)[range_min:range_max] # current page plus up to 10 pages, not including first and last
			context['page_range'].insert(0,1); # first page
			context['page_range'].append(context['paginator'].num_pages);
		return context

	def post(self, request, *args, **kwargs):
		return self.get(request, *args, **kwargs)

class DetailView(generic.DetailView):
	model = Song
	template_name = 'songs/detail.html'

musictable/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Circle of Hope Music Table</title>

    <!-- Bootstrap -->
    <link href="/static/vendor/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/styles.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block header %}
    <div class="jumbotron">
      <div class="container">
        <h1><a href="{% url 'index' %}">CoH Music Table</a></h1>
        <p>A shared resource of music used for worship in the Circle of Hope community.</p>
      </div>
    </div>
    {% endblock %}
    <div class="container">
      {% block pageContent %}
      Page Failed to Load
      {% endblock %}
    </div>
    

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="/static/vendor/jquery/dist/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/static/vendor/bootstrap/dist/js/bootstrap.min.js"></script>
  </body>
</html>

musictable/templates/songs/detail.html
{% extends "layout.html" %}
{% load attachments %}

{% block pageContent %}

<h2>{{ song.title }}</h2>

<div class="row">
	<div class="col-md-8">
		<table class="table table-condensed table-borderless">
			<tr>
				<th scope="row">Title</th>
				<td>{{ song.title }}</td>
			</tr>
			<tr>
				<th scope="row">Author</th>
				<td>{{ song.author }}</td>
			</tr>
			<tr>
				<th scope="row">Scripture</th>
				<td>{{ song.scripture }}</td>
			</tr>
			<tr>
				<th scope="row">First Line</th>
				<td>{{ song.first_line }}</td>
			</tr>
			<tr>
				<th scope="row">Lyrics Excerpt</th>
				<td>{{ song.key_lyric }}</td>
			</tr>
			<tr>
				<th scope="row">Notes</th>
				<td>{{ song.notes }}</td>
			</tr>
		</table>

		<h3>Attachments</h3>
		{% if song.attachment_set.count %}
			<table class="table table-condensed table-borderless">
				<tr>
					<th>Name</th>
					<th>Location</th>
					<th>&nbsp;</th>
				</tr>
			{% for attachment in song.attachment_set.all %}
				<tr>
					<td>{{ attachment.name }}</td>
					<td>{{ attachment.location | displayLink }}</td>
					<td><a href="{{ attachment.location }}" target="_blank">View</a></td>
				</tr>
			{% endfor %}
			</table>
		{% endif %}
	</div>
	<div class="col-md-4">
		{% regroup song.tags.all|dictsort:"type_id" by type as tagTypes %}

		{% for tagType in tagTypes %}
		<h4>{{ tagType.grouper }}</h4>
			{% for tag in tagType.list %}
			<span class="label label-primary">{{ tag.name }}</span>
			{% endfor %}
		{% endfor %}

	</div>
</div>

{% endblock %}

musictable/templates/songs/index.html
{% extends "layout.html" %}

{% block pageContent %}

<form method="post" class="form-inline">
	{% csrf_token %}
  <div class="form-group">
    <input type="text" class="form-control" id="search" name="search">
  </div>
  <button type="submit" class="btn btn-primary">Search</button>
</form>

<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th>Title</th>
			<th>Artist</th>
			<th>First Line</th>
			<th>&nbsp</th>
		</tr>
	</thead>

	<tbody>
	{% for song in song_list %}
		<tr>
			<td>{{ song.title }}</td>
			<td>{{ song.author }}</td>
			<td>{{ song.first_line }}</td>
			<td><a href="{% url 'detail' song.id %}">View</a></td>
		</tr>
	{% endfor %}
	</tbody>

</table>

{% if is_paginated %}
<nav>
  <ul class="pagination">
    <li>
      {% if page_obj.has_previous %}<a href="{% url 'index' %}?page={{ page_obj.previous_page_number }}" aria-label="Previous">{% endif %}
        <span aria-hidden="true">&laquo;</span>
      {% if page_obj.has_previous %}</a>{% endif %}
    </li>
		{% for page in page_range %}
	    <li{% if page_obj.number = page %} class="active"{% endif %}><a href="{% url 'index' %}?page={{ page }}">{{ page }}</a></li>
	  {% endfor %}
    <li>
      {% if page_obj.has_next %}<a href="{% url 'index' %}?page={{ page_obj.next_page_number }}" aria-label="Next">{% endif %}
        <span aria-hidden="true">&raquo;</span>
      {% if page_obj.has_next %}</a>{% endif %}
    </li>
  </ul>
</nav>
{% endif %}

{% endblock %}